// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzsvzvxsqcdymsqbrefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6c3Z6dnhzcWNkeW1zcWJyZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDM4NzksImV4cCI6MjA2MjgxOTg3OX0.m34ihIu69kce0U5qwZA0FYDNfNIY61to2LTMaGjor2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});